# .github/dependabot.yml
version: 2
updates:
  - package-ecosystem: "npm" # Specify npm as the package ecosystem
    directory: "/" # Location of your package.json and package-lock.json
    schedule:
      interval: "weekly" # Dependabot checks for updates every week
