name = "trainercentral-update-workflow"
type = "javascript"
main = "src/index.js"
compatibility_date = "2025-01-19"

workers_dev = true

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true
