name = "trainercentral-update-workflow"
type = "javascript"
main = "src/index.js"

account_id = "YOUR_ACCOUNT_ID"
workers_dev = true
kv_namespaces = [
  { binding = "KV_TCUK", id = "YOUR_KV_NAMESPACE_ID" }
]
